# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: 'configure-vs-cmake'
'on':
  push:
    branches:
      - master
    paths:
      - '*.ac'
      - '**/*.m4'
      - '**/CMakeLists.txt'
      - 'CMake/**'
      - 'lib/curl_config-cmake.h.in'
      - 'tests/cmake/**'
      - '.github/scripts/cmp-config.pl'
      - '.github/workflows/configure-vs-cmake.yml'

  pull_request:
    branches:
      - master
    paths:
      - '*.ac'
      - '**/*.m4'
      - '**/CMakeLists.txt'
      - 'CMake/**'
      - 'lib/curl_config-cmake.h.in'
      - 'tests/cmake/**'
      - '.github/scripts/cmp-config.pl'
      - '.github/workflows/configure-vs-cmake.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  DO_NOT_TRACK: '1'

jobs:
  check-linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 'run configure --with-openssl'
        run: |
          autoreconf -fi
          export PKG_CONFIG_DEBUG_SPEW=1
          mkdir bld-am && cd bld-am && ../configure --enable-static=no --with-bearssl --without-libpsl

      - name: 'run cmake'
        run: cmake -B bld-cm -DCURL_WERROR=ON -DCURL_USE_CMAKECONFIG=OFF -DCURL_USE_LIBPSL=OFF

      - name: 'configure log'
        run: cat bld-am/config.log 2>/dev/null || true

      - name: 'cmake log'
        run: cat bld-cm/CMakeFiles/CMakeConfigureLog.yaml 2>/dev/null || true

      - name: 'dump generated files'
        run: |
          for f in libcurl.pc curl-config; do
            echo "::group::AM ${f}"; grep -v '^#' bld-am/"${f}" || true; echo '::endgroup::'
            echo "::group::CM ${f}"; grep -v '^#' bld-cm/"${f}" || true; echo '::endgroup::'
          done

      - name: 'compare generated curl_config.h files'
        run: ./.github/scripts/cmp-config.pl bld-am/lib/curl_config.h bld-cm/lib/curl_config.h

      - name: 'compare generated libcurl.pc files'
        run: ./.github/scripts/cmp-pkg-config.sh bld-am/libcurl.pc bld-cm/libcurl.pc

      - name: 'compare generated curl-config files'
        run: ./.github/scripts/cmp-pkg-config.sh bld-am/curl-config bld-cm/curl-config
